import { headers } from "next/headers";
import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { getAuth } from "@/lib/auth/auth";
import { Brand } from "@/components/home/home-marks";
import { DashboardUnavailableError, getDashboard } from "@/modules/dashboard/dashboard.service";

export const dynamic = "force-dynamic";
export const metadata = { title: "Your wedding dashboard | Make My Marriage", robots: { index: false, follow: false } };
const upcoming = [
  { title: "Your celebrations", label: "Events", icon: "✧", copy: "Give Haldi, Mehndi, Sangeet, and every celebration its own date, venue, and plan." },
  { title: "Your tasks", label: "Tasks", icon: "✓", copy: "Assign responsibilities, set due dates, and keep track of the little details." },
  { title: "Event guests & RSVP", label: "Guests & RSVP", icon: "♡", copy: "Prepare separate guest lists and personalized RSVP links for each celebration." },
  { title: "Vendor contacts", label: "Vendors", icon: "◇", copy: "Keep your caterer, photographer, and other planning contacts together." },
  { title: "Setup & inspiration", label: "Setup references", icon: "❋", copy: "Save private images and notes for your ceremony décor and arrangements." },
];
export default async function DashboardPage({ params }: { params: Promise<{ weddingId: string }> }) {
  const session = await (await getAuth()).api.getSession({ headers: await headers() });
  if (!session || !session.user.emailVerified) redirect("/login");
  const { weddingId } = await params;
  let data;
  try { data = await getDashboard(session.user.id, weddingId); } catch (error) { if (error instanceof DashboardUnavailableError) notFound(); throw error; }
  const familyUrl = `/weddings/${weddingId}/family`;
  const displayDate = new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${data.wedding.weddingDate}T00:00:00Z`));
  return <div className="dashboard-shell"><a className="skip-link" href="#dashboard-main">Skip to dashboard</a>
    <aside className="dashboard-sidebar"><Brand /><div className="dashboard-wedding-switch"><p className="eyebrow">YOUR WEDDING</p><h2>{data.wedding.title}</h2><p>{displayDate}</p><span className="family-badge">{data.countdown.label}</span></div><nav aria-label="Wedding navigation"><Link className="dashboard-nav-active" aria-current="page" href={`/weddings/${weddingId}/dashboard`}>◫ Dashboard</Link><Link href={familyUrl}>{data.access.canManageFamily ? "♡ Family & invitations" : "♡ Your access"}</Link>{upcoming.map(item => <span key={item.label}>{item.icon} {item.label}<small>Coming soon</small></span>)}{data.finance.visible && <span>₹ Expenses<small>Coming soon</small></span>}</nav><Link className="dashboard-switch-link" href="/weddings">Switch wedding →</Link><Link className="dashboard-switch-link" href="/">Visit homepage →</Link></aside>
    <div className="dashboard-body"><header className="dashboard-topbar"><span className="dashboard-mobile-brand"><Brand /></span><span className="dashboard-context">Your wedding workspace</span><Link className="dashboard-account" href="/login"><span>{session.user.name || "Your account"}<small>{data.access.role === "OWNER" ? "Owner" : data.access.role === "EDITOR" ? "Editor" : "Viewer"}</small></span><span className="dashboard-avatar" aria-hidden="true">{(session.user.name || "You").slice(0, 1).toUpperCase()}</span></Link></header>
      <main id="dashboard-main" className="dashboard-main"><section className="dashboard-heading"><div><p className="eyebrow">YOUR WEDDING, TOGETHER</p><p className="dashboard-greeting">Welcome, {session.user.name || "friend"}.</p><h1>{data.wedding.title}</h1><div className="dashboard-tags"><span>{displayDate}</span><span>{data.countdown.label}</span>{data.wedding.city && <span>{data.wedding.city}</span>}</div></div><Link className="button" href={familyUrl}>{data.access.canManageFamily ? "Invite your family →" : "View your access →"}</Link></section>
        <section className="dashboard-hero"><div><p className="eyebrow">A LITTLE MORE TOGETHER</p><h2>A place for every<br /><em>part of your story.</em></h2><p>Your wedding details are saved. Bring your people into the plan, and make room for the celebrations ahead.</p><Link className="text-link" href={familyUrl}>{data.access.canManageFamily ? "Manage family & invitations" : "Your role & permissions"} →</Link></div><div className="dashboard-hero-photo"><Image src="/images/wedding-couple.jpg" alt="An Indian couple celebrating their wedding" fill priority sizes="(max-width: 760px) 90vw, 40vw" /></div></section>
        <div className="dashboard-working-grid"><section className="dashboard-card"><p className="eyebrow">YOUR PLACE IN THE PLAN</p><h2>Your access</h2><span className="family-badge">{data.access.role}</span>{data.access.relationship && <p className="dashboard-relationship">{data.access.relationship}</p>}<ul className="dashboard-permissions"><li>{data.access.canManagePlanning ? "Can help manage wedding planning as features become available." : "Can view wedding planning without making changes."}</li><li>{data.finance.visible ? "Budget and expense access granted. Financial planning is coming soon." : "No access to private financial information."}</li><li>{data.access.canManageFamily ? "Can invite family, change permissions, and remove members." : "Can view your own access. Family management and member lists are Owner-only."}</li></ul></section>
        {data.family && <section className="dashboard-card"><p className="eyebrow">OWNER OVERVIEW</p><h2>Family & invitations</h2><div className="dashboard-family-counts"><div><strong>{data.family.joined}</strong><span>Joined collaborators</span></div><div><strong>{data.family.pending}</strong><span>Awaiting acceptance</span></div><div><strong>{data.family.expired}</strong><span>Expired</span></div><div><strong>{data.family.revoked}</strong><span>Revoked</span></div></div><p>See who has joined, their relationship and permissions, and who still needs to accept.</p><Link className="text-link" href={familyUrl}>Open family & invitations →</Link></section>}</div>
        <section id="coming-next" className="dashboard-upcoming"><div className="dashboard-section-heading"><p className="eyebrow">WHAT COMES NEXT</p><h2>More room for your plans.</h2><p>These sections are planned for the next stages. They aren’t available yet.</p></div><div className="dashboard-feature-grid">{upcoming.map(item => <article className="dashboard-card upcoming-card" key={item.title}><span className="dashboard-feature-icon" aria-hidden="true">{item.icon}</span><span className="dashboard-soon">Coming soon</span><h3>{item.title}</h3><p>{item.copy}</p></article>)}{data.finance.visible && <article className="dashboard-card upcoming-card"><span className="dashboard-feature-icon" aria-hidden="true">₹</span><span className="dashboard-soon">Coming soon</span><h3>Budgets & expenses</h3><p>Track estimates, committed expenses, manually recorded payments, and outstanding dues.</p></article>}</div></section>
        <footer className="dashboard-footer">Make My Marriage · A little more together.<Link href="/weddings">My weddings →</Link></footer>
      </main><nav className="dashboard-mobile-nav" aria-label="Mobile wedding navigation"><Link aria-current="page" href={`/weddings/${weddingId}/dashboard`}>Dashboard</Link><Link href={familyUrl}>{data.access.canManageFamily ? "Family" : "Your access"}</Link><Link href="/weddings">Weddings</Link><Link href="/login">Account</Link></nav></div>
  </div>;
}
