import Image from "next/image";
import { CeremonyPreview, HomeHeader, PlanningButton } from "@/components/home/home-interactions";
import { Arrow, Brand, Flower } from "@/components/home/home-marks";

const steps = [
  { number: "01", title: "Dream it together", text: "Give your celebration a name, choose a date, and make room for everything you imagine.", tag: "YOUR WEDDING WORKSPACE", symbol: "✧" },
  { number: "02", title: "Make a little plan", text: "From the first Haldi to the last dance, bring your events, tasks, and budget into one place.", tag: "EVERY DETAIL, CONNECTED", symbol: "❋" },
  { number: "03", title: "Bring your people", text: "Invite the family, share responsibilities, and turn a hundred little to-dos into a team effort.", tag: "BETTER, TOGETHER", symbol: "♡" },
];

export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a><HomeHeader />
    <main id="main">
      <section className="hero section-width" aria-labelledby="hero-title">
        <div className="hero-copy"><p className="eyebrow"><span className="small-rule" /> MADE FOR INDIAN CELEBRATIONS</p><h1 id="hero-title">A little less planning.<br />A lot more <em>love.</em></h1><p className="intro">From the first yes to the final dance, bring your wedding, your plans, and your favourite people together. All in one beautiful place.</p><div className="hero-actions"><PlanningButton /><a className="text-link" href="#how-it-works">See how it works <Arrow /></a></div><div className="hero-note"><span className="mini-flower"><Flower /></span><span>Thoughtfully made for couples.<br /><strong>And everyone who makes it happen.</strong></span></div></div>
        <div className="hero-visual"><div className="hero-photo"><Image src="/images/wedding-couple.jpg" alt="An Indian bride and groom sharing a quiet moment in an Udaipur courtyard" fill priority sizes="(max-width: 760px) 92vw, 48vw" /><span className="photo-caption">THE BEGINNING OF YOUR FOREVER</span></div><span className="hero-ornament" aria-hidden="true"><Flower /></span><div className="milestone-card"><span className="milestone-icon" aria-hidden="true">♡</span><div><span className="eyebrow">A LITTLE PREVIEW</span><strong>Your day. Your way.</strong><span>Every lovely detail, in its place.</span></div><span className="status-dot" aria-hidden="true" /></div><span className="vertical-note" aria-hidden="true">A CELEBRATION AS UNIQUE AS YOU</span></div>
      </section>
      <div className="promise-strip"><span>Many celebrations.</span><Flower /><span>One shared plan.</span><Flower /><span>All your favourite people.</span><Flower /><span>A little more peace of mind.</span></div>
      <section id="how-it-works" className="journey section-width section-space"><div className="section-heading"><p className="eyebrow">FROM “WE SAID YES” TO “WE DO”</p><h2>Big celebrations.<br /><em>Beautifully simple beginnings.</em></h2><p>You don’t need to have it all figured out.<br />Just start with the two of you. We’ll help you organise the rest.</p></div><div className="journey-grid">{steps.map((step) => <article className="journey-step" key={step.number}><div className="step-top"><span className="step-symbol" aria-hidden="true">{step.symbol}</span><span className="step-number">{step.number}</span></div><h3>{step.title}</h3><p>{step.text}</p><span className="step-tag">{step.tag}</span></article>)}</div></section>
      <section id="celebrations" className="celebrations section-space"><div className="section-width"><div className="split-heading"><div><p className="eyebrow">EVERY RITUAL. EVERY LITTLE MOMENT.</p><h2>One love story.<br /><em>So many reasons to celebrate.</em></h2></div><p>The yellow of Haldi. The music of Sangeet. The magic of your wedding day. Give every celebration its own space, without losing the bigger picture.</p></div><CeremonyPreview /></div></section>
      <section id="together" className="together section-width section-space"><div className="family-visual"><div className="family-photo"><Image src="/images/family-planning.jpg" alt="Family members gathered around a tablet to plan a wedding together" fill sizes="(max-width: 760px) 90vw, 44vw" /></div><div className="task-preview"><div className="preview-heading"><span className="eyebrow">THE LITTLE THINGS, TAKEN CARE OF</span><span className="preview-label">Example</span></div><div className="task-row"><span className="task-check">✓</span><span>Pick the Sangeet playlist<small>Assigned to Riya · Sister</small></span><span className="avatar">R</span></div><div className="task-row"><span className="task-check">✓</span><span>Confirm the flowers<small>Assigned to Mum</small></span><span className="avatar gold">M</span></div></div></div><div className="feature-copy"><p className="eyebrow">YOUR WEDDING. YOUR PEOPLE.</p><h2>A family affair.<br /><em>Without the family chaos.</em></h2><p>There’s always a cousin with a playlist, an uncle with a contact, and a mum with a list. Give everyone a place in the plan.</p><ul className="feature-list"><li><span>01</span><div><strong>Share the joy. And the to-dos.</strong><p>Assign tasks so everyone knows what’s theirs.</p></div></li><li><span>02</span><div><strong>Keep everyone on the same page.</strong><p>One shared place for dates, details, and updates.</p></div></li><li><span>03</span><div><strong>Let the right people see the right things.</strong><p>Choose who can edit, view, or help with the budget.</p></div></li></ul><PlanningButton className="text-link" label="Make room for your people" /></div></section>
      <section id="details" className="details-section section-space"><div className="section-width"><div className="section-heading"><p className="eyebrow">LESS SCATTERED. MORE SETTLED.</p><h2>For all the details<br /><em>that make it yours.</em></h2></div><div className="detail-grid">
        <article className="detail-card"><div className="invitation-art" aria-label="Example invitation for Aarav and Nisha’s wedding"><div className="invitation-paper"><Flower /><span>TOGETHER WITH OUR FAMILIES</span><strong>Aarav <em>&</em> Nisha</strong><span>JOYFULLY INVITE YOU TO THEIR WEDDING</span><div className="invitation-date">14 <i>FEBRUARY</i> 2027</div><span>UDAIPUR, RAJASTHAN</span><div className="paper-rule" /></div><span className="art-label">INVITATION PREVIEW</span></div><div className="detail-copy"><span className="eyebrow">AN INVITATION TO REMEMBER</span><h3>A warm welcome, one link away.</h3><p>Share personal event invitations and keep track of who’s joining each celebration. No guest account needed.</p></div></article>
        <article className="detail-card"><div className="budget-art"><div className="budget-top"><span>Our wedding budget</span><span className="preview-label">Example</span></div><span className="budget-caption">PLANNED BUDGET</span><strong className="budget-total">₹12,00,000</strong><div className="budget-track"><span /></div><div className="budget-key"><span><i />Paid <strong>₹4,50,000</strong></span><span><i />Outstanding <strong>₹3,50,000</strong></span></div><div className="budget-foot"><span>Committed expenses</span><strong>₹8,00,000</strong></div></div><div className="detail-copy"><span className="eyebrow">MORE CLARITY. FEWER SURPRISES.</span><h3>Happy hearts. A settled budget.</h3><p>Keep estimates, expenses, and recorded payments together. Know what’s paid and what’s still to come.</p></div></article>
        <article className="detail-card inspiration-card"><div className="inspiration-photo"><Image src="/images/wedding-details.jpg" alt="Wedding stationery and carefully chosen details for a celebration moodboard" fill sizes="(max-width: 760px) 90vw, 30vw" /><span className="inspiration-note">The little things are the big things.</span></div><div className="detail-copy"><span className="eyebrow">YOUR VISION, ALL TOGETHER</span><h3>A place for every lovely idea.</h3><p>Save décor references, add notes, and keep vendor contacts close. Turn “something like this” into a shared vision.</p></div></article>
      </div></div></section>
      <section className="faq section-width section-space"><div><p className="eyebrow">A FEW THINGS YOU MIGHT BE WONDERING</p><h2>A little clarity,<br /><em>before you begin.</em></h2><Flower /></div><div className="faq-list">{[
        ["Can we plan more than one wedding function?", "Yes. Your wedding workspace is designed for Haldi, Mehndi, Sangeet, your ceremony, reception, and custom events. Each event has its own details, tasks, expenses, and guests."],
        ["Can our family help us plan?", "That’s the idea. Invite family members as editors or viewers, assign responsibilities, and choose who can access financial details."],
        ["Do our guests need to create an account?", "No. Guests will be able to open their personal event invitation link and accept or decline without an organizer account."],
        ["What happens when I start planning today?", "This early preview lets you save your wedding name, date, and city as a draft in this browser. Accounts and shared wedding workspaces are still being built. Your draft is not shared with anyone or saved to a server."],
      ].map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="closing"><div className="closing-decoration" aria-hidden="true"><Flower /></div><div className="closing-content"><p className="eyebrow">THE NEXT CHAPTER IS YOURS</p><h2>Make memories.<br /><em>We’ll make room for the plans.</em></h2><p>A celebration full of love starts with a little space to dream.</p><PlanningButton className="button button-cream" /><span className="closing-note">For the two of you. And the people you love.</span></div></section>
    </main>
    <footer className="footer section-width"><div><Brand /><p>Your wedding. One place. A little more joy.</p></div><nav aria-label="Footer"><a href="#how-it-works">How it works</a><a href="#celebrations">Celebrations</a><a href="#together">For your family</a></nav><span className="footer-note">Made for love.<br />Rooted in Indian celebrations.</span></footer>
  </>;
}
